### ISSUE TITLE
Feature Request: match history/log

### ISSUE THREAD

**Issue by jhkl33** [sarahkittyy/KeywordTracker#4] opened 2021-07-03 17:29 UTC
Hi! 

It would be much appreciated if you could add some sort of log or history with an overview of past matches. I get random pings but sometimes I don't get a desktop notification (if you disable desktop notifications you get nothing but the ping sound), and I have no idea which keyword or server triggered it. Searching and checking every one would be pain, so a simple log with timestamps would make it a lot easier.

Cheers, love the work you've done!

**Comment by sarahkittyy** [comment] 2021-07-03 19:47
Duplicate of #1, this is on my to-do list :)

**Closed by sarahkittyy** 2021-07-03 19:47 UTC
Labels: duplicate
