### ISSUE TITLE
Show keyword pings visually

### ISSUE THREAD

**Issue by Kuuuube** [sarahkittyy/KeywordTracker#10] opened 2021-07-23 16:09 UTC
Notifications don't have any visuals attached to them making it very hard to find where the notification is from.

I'm a bit confused here because there was already an issue made on this: https://github.com/sarahkittyy/KeywordTracker/issues/6. And it was said to be added/fixed. I made sure I am on the latest version and I can't find any settings that would change this.

I'm sorry if this is just me not knowing what to do but if that is the case it would be nice to have some some documentation on the feature.

**Comment by Matteoki** [comment] 2021-07-30 20:42
oh i thought it was just my problem, so i didn't reply back.

**Comment by sarahkittyy** [comment] 2021-08-18 20:31
@Kuuuube @Matteoki Oh, I think I just misinterpreted the original issue, lmao-- in the commit that I claimed to have fixed it, all I did was add text in the notification telling you what server it came from. What you're actually looking for is just a duplicate of #1, which I am actually getting to work on as I type this.

**Closed by sarahkittyy** 2021-08-18 20:31 UTC
Labels: duplicate
