### ISSUE TITLE
FR: regex in embed names

### ISSUE THREAD

**Issue by MitchelValentine** [sarahkittyy/KeywordTracker#37] opened 2022-01-25 08:46 UTC
I want to be notified when specific links are posted (etc https://i.imgur.com), but the plugin doesn't look in the links/embed names.

**Comment by sarahkittyy** [comment] 2022-01-25 18:48
Afaik this is a duplicate of #16? If it's not, then my bad, open a new issue :)

**Closed by sarahkittyy** 2022-01-25 18:48 UTC
Labels: duplicate
