### ISSUE TITLE
embed messages from bot didn't get notified

### ISSUE THREAD

**Issue by ju0nsus** [sarahkittyy/KeywordTracker#19] opened 2021-08-30 04:33 UTC
sorry for bringing this up again, but i really appreciate you're doing this plugin. but getting a notification from embed messages is hell yes for me :>
![image](https://user-images.githubusercontent.com/89762889/131285576-b8998384-eab4-44a4-875b-410e01577bfb.png)

**Comment by sarahkittyy** [comment] 2022-01-25 05:40
I appreciate the positive encouragement but I will close this to stay organized as it's a duplicate of #16

**Closed by sarahkittyy** 2022-01-25 05:40 UTC
