### ISSUE TITLE
No longer working on new version?

### ISSUE THREAD

**Issue by ImDini** [sarahkittyy/KeywordTracker#31] opened 2021-12-29 06:11 UTC
The button doesn't exist anymore and it's enabled

**Comment by Kuuuube** [comment] 2021-12-29 16:55
Got this same issue. It appears to be caused by something on initial startup of discord. Disabling and enabling that plugin then flipping through a few servers got the button back for me on that instance of discord.

**Comment by ImDini** [comment] 2021-12-29 23:47
> Got this same issue. It appears to be caused by something on initial startup of discord. Disabling and enabling that plugin then flipping through a few servers got the button back for me on that instance of discord.

Yeah this as well as it still "works" I still get notifications just no where to open them in app unless I click the windows notification it gives.

**Comment by sarahkittyy** [comment] 2022-01-01 21:28
Fixed in e08037! :)

**Closed by sarahkittyy** 2022-01-01 21:28 UTC
